
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.8.0-1017-azure - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCCompilerFlag.cmake:56 (cmake_check_compiler_flag)"
      - "lib/extern/raylib/cmake/AddIfFlagCompiles.cmake:3 (CHECK_C_COMPILER_FLAG)"
      - "lib/extern/raylib/cmake/CompilerFlags.cmake:5 (add_if_flag_compiles)"
      - "lib/extern/raylib/CMakeLists.txt:34 (include)"
    checks:
      - "Performing Test COMPILER_HAS_THOSE_TOGGLES"
    directories:
      source: "/home/runner/work/platformer-game/platformer-game/build_web/CMakeFiles/CMakeScratch/TryCompile-QEM9oj"
      binary: "/home/runner/work/platformer-game/platformer-game/build_web/CMakeFiles/CMakeScratch/TryCompile-QEM9oj"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps-18"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/platformer-game/platformer-game/emsdk-cache/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/platformer-game/platformer-game/emsdk-cache/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/platformer-game/platformer-game/emsdk-cache/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/platformer-game/platformer-game/emsdk-cache/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/platformer-game/platformer-game/emsdk-cache/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/platformer-game/platformer-game/lib/extern/raylib/cmake"
    buildResult:
      variable: "COMPILER_HAS_THOSE_TOGGLES"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/platformer-game/platformer-game/build_web/CMakeFiles/CMakeScratch/TryCompile-QEM9oj'
        
        Run Build Command(s): /usr/bin/ninja -v cmTC_1c519
        [1/2] /home/runner/work/platformer-game/platformer-game/emsdk-cache/emsdk-main/upstream/emscripten/emcc -DCOMPILER_HAS_THOSE_TOGGLES  -std=gnu99   -Werror=pointer-arith -MD -MT CMakeFiles/cmTC_1c519.dir/src.c.o -MF CMakeFiles/cmTC_1c519.dir/src.c.o.d -o CMakeFiles/cmTC_1c519.dir/src.c.o -c /home/runner/work/platformer-game/platformer-game/build_web/CMakeFiles/CMakeScratch/TryCompile-QEM9oj/src.c
        shared:INFO: (Emscripten: Running sanity checks)
        [2/2] : && /home/runner/work/platformer-game/platformer-game/emsdk-cache/emsdk-main/upstream/emscripten/emcc   CMakeFiles/cmTC_1c519.dir/src.c.o -o cmTC_1c519.js   && :
        cache:INFO: generating system asset: symbol_lists/ce0f97587d0792dd152ea179253e1ec5225542ea.json... (this will be cached in "/home/runner/work/platformer-game/platformer-game/emsdk-cache/emsdk-main/upstream/emscripten/cache/symbol_lists/ce0f97587d0792dd152ea179253e1ec5225542ea.json" for subsequent builds)
        cache:INFO:  - ok
        
      exitCode: 0
...
