name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.45
          actions-cache-folder: 'emsdk-cache'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential ninja-build

      - name: Initialize Raylib
        run: |
          git submodule update --init --recursive
          ls -la lib/extern/raylib

      - name: Build
        run: |
          mkdir -p build_web
          cd build_web
          emcmake cmake .. -G Ninja \
            -DPLATFORM=Web \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_EXAMPLES=OFF \
            -DUSE_WAYLAND=OFF \
            -DUSE_X11=OFF \
            -DOPENGL_VERSION="ES 2.0"
          ninja

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build_web
          branch: gh-pages 